apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    isDefault: true

    url: http://${INFLUXDB_HOST}:8086

    jsonData:
      version: Flux
      organization: ${INFLUXDB_INIT_ORG}
      defaultBucket: ${INFLUXDB_INIT_BUCKET}
      httpMode: POST

    secureJsonData:
      token: ${INFLUXDB_TOKEN}